name: CI

on:
  pull_request:
  push:
    branches:
      - main

# when new commit is pushed to a branch, cancel previous runs
# https://stackoverflow.com/a/67939898/580181
concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        node: ['20']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8.5.0
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - run: pnpm install

      - run: pnpm build
        env:
          # at the end of the build, upload sourcemaps to sentry but only on main branch
          SENTRY_AUTH_TOKEN: ${{ github.ref == 'refs/heads/main' && secrets.SENTRY_AUTH_TOKEN || '' }}
          SENTRY_ORG: ${{ github.ref == 'refs/heads/main' && secrets.SENTRY_ORG || '' }}
          SENTRY_PROJECT: ${{ github.ref == 'refs/heads/main' && secrets.SENTRY_PROJECT || '' }}

      - uses: krzkaczor/size-limit-action@master
        if: github.ref != 'refs/heads/main'
        with:
          skip_step: build # already built
          directory: packages/app
          github_token: ${{ secrets.GITHUB_TOKEN }}
          package_manager: pnpm

  test:
    strategy:
      matrix:
        node: ['20']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8.5.0
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - run: pnpm install

      - run: pnpm lint
      - run: pnpm format
      - run: pnpm run test
      - run: pnpm typecheck

  storybook-visual-regression:
    strategy:
      matrix:
        node: ['20']
        os: [ubicloud-standard-4]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8.5.0
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - run: pnpm install

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          workingDir: packages/app
          buildScriptName: storybook:build
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: main

  test-e2e:
    strategy:
      fail-fast: false
      matrix:
        node: ['20']
        os: [ubicloud-standard-16]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8.5.0
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - run: pnpm install

      - run: pnpm exec playwright install --with-deps chromium
        working-directory: ./packages/app
      - run: pnpm run test-e2e
        working-directory: ./packages/app
        env:
          TENDERLY_API_KEY: '${{ secrets.TENDERLY_API_KEY }}'
          TENDERLY_ACCOUNT: phoenixlabs
          TENDERLY_PROJECT: sparklend
          REPLAY_API_KEY: ${{ secrets.REPLAY_API_KEY }}

      - uses: krzkaczor/reg-actions@action-v2
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          image-directory-path: './packages/app/__screenshots-e2e__'
          collection-name: 'e2e'
          threshold-pixel: 5
          matching-threshold: 0.09
